name: Build pipeline (Runthepipeline → Excel)

on:
  workflow_dispatch:    # correrlo a mano desde Actions
  schedule:
    - cron: "0 3 * * *"   # todos los días 03:00 UTC (00:00 aprox. ART)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # para poder commitear los archivos generados

    env:
      # Cambiá la lista de tickers acá
      TICKERS: "KO,PEP,MNST,AAPL,MSFT"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          python Runthepipeline.py --tickers "${{ env.TICKERS }}" --use-v2

      # Guarda los Excel como artifact (descargables desde la pestaña del job)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scorecards-excel
          path: |
            *_full.xlsx
            *_key.xlsx
            *_ratios.xlsx
            *_scorecard.xlsx
            Scorecards_*.xlsx

      # (opcional) Commitea los resultados al repo
      - name: Commit results to repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add *_full.xlsx *_key.xlsx *_ratios.xlsx *_scorecard.xlsx Scorecards_*.xlsx || true
          git commit -m "data: update scorecards (tickers=${{ env.TICKERS }})" || echo "No changes to commit"
          git push || true
